[package]
name = "fin-cli"
version = "0.1.0"
authors = ["Brian <henninb@msn.com>"]

[dependencies]
#rocket = "0.3.16"
#rocket_codegen = "0.3.16"
#hyper = "0.10"
hyper = "0.12.10"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"
pretty_env_logger = "0.2.4"
http = "0.1.13"